# Generated by Django 2.0.2 on 2018-03-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_message_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.IntegerField(choices=[(0, 'Unknown'), (10, 'Patient'), (20, 'Doctor'), (30, 'Admin'), (40, 'Lab')], default=0),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Account'), (2, 'Patient'), (3, 'Admin'), (4, 'Appointment'), (5, 'Medical Test'), (6, 'Prescription'), (7, 'Message'), (8, 'Medical Info'), (9, 'Lab')], default=0),
        ),
    ]
