# Generated by Django 2.0.2 on 2018-03-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20180306_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
