# Generated by Django 2.0.2 on 2018-03-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_appointment_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
