# Generated by Django 2.1.2 on 2018-10-31 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_appointment_symptom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='speciality',
            field=models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Speciality'),
        ),
    ]
